spring:
    application:
        name: booksapi

    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/books_java?schema=test}
        username: ${DATABASE_USERNAME:dev}
        password: ${DATABASE_PASSWORD:dev}
        driver-class-name: org.postgresql.Driver

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    
    flyway:
        enabled: true
        locations: classpath:db/migration